import { describe, it, expect } from 'vitest'
import { generateFormPdfHtml } from '@/lib/services/pdf-generator'

describe('PDF Generator Service', () => {
  const baseData = {
    clinicName: 'Test Dental Clinic',
    clinicAddress: '123 Main St',
    clinicPhone: '9876543210',
    clinicEmail: 'clinic@test.com',
    patientName: 'John Doe',
    patientId: 'PAT202600001',
    patientPhone: '9876543211',
    patientDob: '1990-01-15',
    formTitle: 'Consent Form',
    formType: 'CONSENT',
    submittedAt: '2026-03-01T10:00:00Z',
    fields: [
      { label: 'Treatment', value: 'Root Canal', type: 'text' },
      { label: 'Agreed', value: 'Yes', type: 'checkbox' },
    ],
  }

  it('generates valid HTML document with all required sections', () => {
    const html = generateFormPdfHtml(baseData)
    expect(html).toContain('<!DOCTYPE html>')
    expect(html).toContain('Test Dental Clinic')
    expect(html).toContain('123 Main St')
    expect(html).toContain('John Doe')
    expect(html).toContain('PAT202600001')
    expect(html).toContain('Consent Form')
    expect(html).toContain('Root Canal')
    expect(html).toContain('Yes')
  })

  it('includes clinic contact info', () => {
    const html = generateFormPdfHtml(baseData)
    expect(html).toContain('9876543210')
    expect(html).toContain('clinic@test.com')
  })

  it('includes patient details', () => {
    const html = generateFormPdfHtml(baseData)
    expect(html).toContain('John Doe')
    expect(html).toContain('PAT202600001')
    expect(html).toContain('9876543211')
    expect(html).toContain('1990-01-15')
  })

  it('renders fields as table rows', () => {
    const html = generateFormPdfHtml(baseData)
    expect(html).toContain('field-label')
    expect(html).toContain('Treatment')
    expect(html).toContain('Root Canal')
  })

  it('includes signature block when signature is provided', () => {
    const data = {
      ...baseData,
      signature: 'data:image/png;base64,iVBORw0KGgo=',
      signedAt: '2026-03-01T10:05:00Z',
    }
    const html = generateFormPdfHtml(data)
    expect(html).toContain('Patient Signature')
    expect(html).toContain('signature-image')
    expect(html).toContain('data:image/png;base64,iVBORw0KGgo=')
    expect(html).toContain('Signed on:')
  })

  it('omits signature block when no signature', () => {
    const html = generateFormPdfHtml(baseData)
    expect(html).not.toContain('Patient Signature')
    expect(html).not.toContain('<img src=')
  })

  it('escapes HTML special characters to prevent XSS', () => {
    const data = {
      ...baseData,
      patientName: '<script>alert("xss")</script>',
      clinicName: "Dr. O'Brien & Associates",
      fields: [{ label: 'Note', value: 'a < b && c > d' }],
    }
    const html = generateFormPdfHtml(data)
    expect(html).not.toContain('<script>')
    expect(html).toContain('&lt;script&gt;')
    expect(html).toContain('&amp;')
    expect(html).toContain('O&#039;Brien')
    expect(html).toContain('a &lt; b &amp;&amp; c &gt; d')
  })

  it('handles optional clinic fields gracefully', () => {
    const data = {
      ...baseData,
      clinicAddress: undefined,
      clinicPhone: undefined,
      clinicEmail: undefined,
      patientId: undefined,
      patientPhone: undefined,
      patientDob: undefined,
    }
    const html = generateFormPdfHtml(data)
    expect(html).toContain('Test Dental Clinic')
    expect(html).toContain('John Doe')
    // Should not crash
    expect(html).toContain('<!DOCTYPE html>')
  })

  it('handles empty fields array', () => {
    const data = { ...baseData, fields: [] }
    const html = generateFormPdfHtml(data)
    expect(html).toContain('<table>')
    expect(html).toContain('</table>')
  })

  it('includes print media query styles', () => {
    const html = generateFormPdfHtml(baseData)
    expect(html).toContain('@media print')
    expect(html).toContain('.no-print')
  })

  it('includes footer with clinic name', () => {
    const html = generateFormPdfHtml(baseData)
    expect(html).toContain('Generated by')
    expect(html).toContain('Shiv Solutions')
  })
})
